### ISSUE TITLE
Issue with Airflow in deployment // uncompliant deployment

### ISSUE THREAD

**Issue by mehmetkadriumay** [Azure/osdu-developer#190]
kind: Event
apiVersion: v1
metadata:
  name: airflow-scheduler-6fcfd954d5-6jl8d.17f26fde9e92d7ed
  namespace: airflow
  uid: 69901404-b370-48ab-89ac-dffcbc6103ab
  resourceVersion: '24506'
  creationTimestamp: '2024-09-05T19:30:09Z'
  managedFields:
    - manager: kubelet
      operation: Update
      apiVersion: v1
      time: '2024-09-05T19:31:29Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:count: {}
        f:firstTimestamp: {}
        f:involvedObject: {}
        f:lastTimestamp: {}
        f:message: {}
        f:reason: {}
        f:reportingComponent: {}
        f:reportingInstance: {}
        f:source:
          f:component: {}
          f:host: {}
        f:type: {}
involvedObject:
  kind: Pod
  namespace: airflow
  name: airflow-scheduler-6fcfd954d5-6jl8d
  uid: 2287b77a-c8bd-4075-89bd-ecae3b3a94b6
  apiVersion: v1
  resourceVersion: '23314'
  fieldPath: spec.containers{scheduler}
reason: Unhealthy
message: >
  Startup probe failed: Unable to load the config, contains a configuration
  error.

  Traceback (most recent call last):
    File "/usr/local/lib/python3.12/pathlib.py", line 1311, in mkdir
      os.mkdir(self, mode)
  FileNotFoundError: [Errno 2] No such file or directory:
  '/opt/airflow/logs/scheduler/2024-09-05'

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/usr/local/lib/python3.12/logging/config.py", line 581, in configure
      handler = self.configure_handler(handlers[name])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.12/logging/config.py", line 854, in configure_handler
      result = factory(**kwargs)
               ^^^^^^^^^^^^^^^^^
    File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/log/file_processor_handler.py", line 53, in __init__
      Path(self._get_log_directory()).mkdir(parents=True, exist_ok=True)
    File "/usr/local/lib/python3.12/pathlib.py", line 1315, in mkdir
      self.parent.mkdir(parents=True, exist_ok=True)
    File "/usr/local/lib/python3.12/pathlib.py", line 1311, in mkdir
      os.mkdir(self, mode)
  OSError: [Errno 30] Read-only file system: '/opt/airflow/logs/scheduler'

  The above exception was the direct cause of the following exception:

  Traceback (most recent call last):
    File "/home/airflow/.local/bin/airflow", line 5, in <module>
      from airflow.__main__ import main
    File "/home/airflow/.local/lib/python3.12/site-packages/airflow/__init__.py", line 74, in <module>
      settings.initialize()
    File "/home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py", line 531, in initialize
      LOGGING_CLASS_PATH = configure_logging()
                           ^^^^^^^^^^^^^^^^^^^
    File "/home/airflow/.local/lib/python3.12/site-packages/airflow/logging_config.py", line 74, in configure_logging
      raise e
    File "/home/airflow/.local/lib/python3.12/site-packages/airflow/logging_config.py", line 69, in configure_logging
      dictConfig(logging_config)
    File "/usr/local/lib/python3.12/logging/config.py", line 920, in dictConfig
      dictConfigClass(config).configure()
    File "/usr/local/lib/python3.12/logging/config.py", line 588, in configure
      raise ValueError('Unable to configure handler '
  ValueError: Unable to configure handler 'processor'
source:
  component: kubelet
  host: aks-poolz3-18136961-vmss000000
firstTimestamp: '2024-09-05T19:30:09Z'
lastTimestamp: '2024-09-05T19:31:29Z'
count: 9
type: Warning
eventTime: null
reportingComponent: kubelet
reportingInstance: aks-poolz3-18136961-vmss000000

**Comment by danielscholl** [comment]
This has been resolved in the latest release.
